<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Seja Bem-Vindo</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
        }
        .container {
            width: 300px;
            margin: 50px auto;
            background-color: #fff;
            padding: 20px;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        h2 {
            text-align: center;
        }
        p {
            text-align: center;
            font-size: 18px;
            color: #333;
        }
        a p {
            width: 100%;
            background-color: #990000;
            color: white;
            padding: 10px 0;
            margin: 8px 0;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            text-decoration: none;
        }
    </style>
</head>
<body>
<div class="container">
    <h2>Seja Bem-Vindo!</h2>
    <p>Obrigado por fazer login. Você agora está autenticado e pode acessar o conteúdo protegido.</p>
        <a href="/limparSessao.php"><p>Sair</p></a>
</div>

</body>
</html>
